// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace DDona.NewReport.Infra
{
    // Grade
    public class Grade
    {
        public int Id { get; set; } // Id (Primary key)
        public int ProdutoId { get; set; } // ProdutoId (Primary key)
        public int ProdutoLojaId { get; set; } // ProdutoLojaId (Primary key)
        public int Cor1Id { get; set; } // Cor1Id
        public int Cor2Id { get; set; } // Cor2Id
        public int Cor3Id { get; set; } // Cor3Id
        public int TamanhoId { get; set; } // TamanhoId
        public string Referencia { get; set; } // Referencia

        // Foreign keys
        public virtual Cor Cor_Cor1Id { get; set; } // FK_Grade_Cor
        public virtual Cor Cor_Cor2Id { get; set; } // FK_Grade_Cor1
        public virtual Cor Cor_Cor3Id { get; set; } // FK_Grade_Cor2
        public virtual Produto Produto { get; set; } // FK_Grade_Produto
        public virtual Tamanho Tamanho { get; set; } // FK_Grade_Tamanho
    }

}
// </auto-generated>
