// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace DDona.NewReport.Infra
{
    public class NewReportDB : DbContext, INewReportDB
    {
        public DbSet<Cor> Cor { get; set; } // Cor
        public DbSet<Grade> Grade { get; set; } // Grade
        public DbSet<Loja> Loja { get; set; } // Loja
        public DbSet<Marca> Marca { get; set; } // Marca
        public DbSet<Produto> Produto { get; set; } // Produto
        public DbSet<Sysdiagrams> Sysdiagrams { get; set; } // sysdiagrams
        public DbSet<Tamanho> Tamanho { get; set; } // Tamanho
        
        static NewReportDB()
        {
            System.Data.Entity.Database.SetInitializer<NewReportDB>(null);
        }

        public NewReportDB()
            : base("Name=NewReportDB")
        {
        }

        public NewReportDB(string connectionString) : base(connectionString)
        {
        }

        public NewReportDB(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model) : base(connectionString, model)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new CorConfiguration());
            modelBuilder.Configurations.Add(new GradeConfiguration());
            modelBuilder.Configurations.Add(new LojaConfiguration());
            modelBuilder.Configurations.Add(new MarcaConfiguration());
            modelBuilder.Configurations.Add(new ProdutoConfiguration());
            modelBuilder.Configurations.Add(new SysdiagramsConfiguration());
            modelBuilder.Configurations.Add(new TamanhoConfiguration());
        }

        public static DbModelBuilder CreateModel(DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new CorConfiguration(schema));
            modelBuilder.Configurations.Add(new GradeConfiguration(schema));
            modelBuilder.Configurations.Add(new LojaConfiguration(schema));
            modelBuilder.Configurations.Add(new MarcaConfiguration(schema));
            modelBuilder.Configurations.Add(new ProdutoConfiguration(schema));
            modelBuilder.Configurations.Add(new SysdiagramsConfiguration(schema));
            modelBuilder.Configurations.Add(new TamanhoConfiguration(schema));
            return modelBuilder;
        }
        
        // Stored Procedures
    }
}
// </auto-generated>
